ARG nodeVersion
FROM node:$nodeVersion
WORKDIR /home/frontend
COPY ./package.json ./webpack.config.js ./babel.config.js ./env.js ./tslint.json ./tsconfig.json ./jest.config.js ./
RUN npm install && npm cache clean -f
CMD ["npm", "start"]