version: '3.3'

services:
  mongo:
    restart: unless-stopped
    ports:
      - 27017:27017

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        - nodeVersion=$NODE_VERSION
    restart: unless-stopped
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    volumes:
      - ./backend/src:/home/backend/src
      - ./backend/test:/home/backend/test
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - nodeVersion=$NODE_VERSION
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/home/frontend/src
      - ./frontend/test:/home/frontend/test
    environment:
      - NODE_ENV=development

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
      args:
        - nodeVersion=$NODE_VERSION
    restart: unless-stopped
    volumes:
      - ./bot/src:/home/bot/src
      - ./bot/test:/home/bot/test
    environment:
      - NODE_ENV=development
      - BOT_TOKEN=$BOT_TOKEN_DEV

  ocr:
    entrypoint: ['echo', 'Service is disabled']
    restart: 'no'
