version: '3.3'

services:
  mongo:
    restart: always
    build: ./mongo/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongodata:/data/db

  backend:
    env_file: .env
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - nodeVersion=$NODE_VERSION
    depends_on:
      - mongo
    environment:
      - MONGO_URI=$MONGO_URI
      - BACKEND_BASE_PATH=$BACKEND_BASE_PATH
      - BACKEND_PORT=$BACKEND_PORT

  bot:
    env_file: .env
    restart: always
    build:
      context: ./bot
      dockerfile: Dockerfile
      args:
        - nodeVersion=$NODE_VERSION
    depends_on:
      - backend
      - mongo
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - MONGO_URI=$MONGO_URI
      - BACKEND_PORT=$BACKEND_PORT
      - BACKEND_BASE_PATH=$BACKEND_BASE_PATH
      - OCR_SERVICE_PORT=$OCR_SERVICE_PORT

  ocr:
    restart: always
    build: ./ocr

volumes:
  mongodata:
